"""added password field

Revision ID: 6e1480827cea
Revises: 8f1eac32c759
Create Date: 2023-11-28 08:22:52.265145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e1480827cea'
down_revision = '8f1eac32c759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=False))
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=100))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
