"""added username

Revision ID: be8e6e95e0b1
Revises: 5a1f97365860
Create Date: 2023-12-03 19:56:50.551460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be8e6e95e0b1'
down_revision = '5a1f97365860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
