"""added foreign key

Revision ID: d69f52eaf165
Revises: be8e6e95e0b1
Create Date: 2023-12-08 12:36:10.644297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd69f52eaf165'
down_revision = 'be8e6e95e0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['poster_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
